---

- name: Download Nodejs Installer
  command: sudo cd /home/timeoff && sudo curl -sL https://rpm.nodesource.com/setup_12.x | sudo -E bash -
  become: yes

- name: Install Nodejs 
  yum:
    name: nodejs
    state: latest
  become: yes