---

- name: Include Role - common
  include_role: 
    name: common

- name: Include Role - nodejs
  include_role: 
    name: nodejs

- name: Include Role - sqlite
  include_role: 
    name: sqlite
  
- name: Download Nexus Artifact
  get_url: 
    url: "{{ url_repo }}"
    dest: /home/timeoff
    username: admin
    password: nexus123
    timeout: 36000
  become: yes

- name: Change file ownership, group and permissions
  file:
    path: /home/timeoff
    owner: timeoff
    group: timeoff
    mode: '0750'