---

- name: Include Role - common
  include_role: 
    name: common

- name: Include Role - nodejs
  include_role: 
    name: nodejs

- name: Include Role - sqlite
  include_role: 
    name: sqlite
  
- name: Download Nexus Artifact
  get_url: 
    url: "{{ url_repo }}"
    dest: "{{ dest_folder }}"
    username: "{{ nexus_user }}"
    password: "{{ nexus_pass }}"
    timeout: 36000
  become: yes